title: "ibarbitrary's blog"
description: "A personal blog."
baseurl: "/blog"
url: "ibarbitrary.github.io"

#google_analytics: UA-NNNNNNNN-N

header_pages:
  - about.md
  - tags.html

footer: 'follow on <a href="https://instagram.com/IBArbitrary">instagram</a>, <a href="https://github.com/IBArbitrary">github</a>'

plugins:
  - jekyll-seo-tag

markdown: kramdown
