title: "ibarbitrary's blog"
description: "A personal blog."
baseurl: ""
url: ""

#google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - about.md

footer: 'follow on <a href="https://instagram.com/IBArbitrary">instagram</a>'

plugins:
  - jekyll-seo-tag

markdown: kramdown
